### ISSUE TITLE
Identifying Colorful Patches

### ISSUE THREAD

**Issue by geoffreyangus** [laura-rieger/deep-explanation-penalization#1]
Hello all,

First of all, I want to say great job on this paper and thank you so much for making the code available in such a usable fashion. I am trying to reproduce some of your results for the ISIC dataset. Specifically, I am trying to generate labels for benign images that identify the colorful patches. Is this something that can be done using your codebase? Let me know, thanks!

**Comment by laura-rieger** [comment]
Hi Geoffrey, glad that you enjoy the work! Just to make sure, you want to obtain labels identifying images with colorful patches (i.e. image has patch -> 1; image has no patch ->0)?

**Comment by geoffreyangus** [comment]
Yes exactly!

**Comment by laura-rieger** [comment]
In the ISIC archive the images with patches all come from one study. I think the easiest way to get labels would be to download  the ISIC images +metadata (script 00 and 01 in the ISIC folder) and filter for images from the SONIC study. You'll have to make a user on isic-archive.com and change password/ user name in config.json

**Comment by geoffreyangus** [comment]
Awesome. I have downloaded the ISIC images and metadata using these first two scripts. Here's an example of the meta.csv DataFrame:

![image](https://user-images.githubusercontent.com/29719151/72272388-63679a00-35dd-11ea-87b7-f7c6ea92fdd7.png)

It is possible that the study is left out of the metadata script, since it only pulls out the clinical data. Looking at the raw API response, it looks like the following:

![image](https://user-images.githubusercontent.com/29719151/72272941-5303ef00-35de-11ea-9e16-ba98ab11e0ec.png)

Do you recall which field would contain information regarding the type of study? Thanks so much for your help on this.

**Comment by laura-rieger** [comment]
If you go to the gallery on the ISIC website and filter for the SONIC dataset, below the images there's a button "Download as ZIP". Click on that, choose "Download all metadata in ISIC archive" and you'll get a zipped folder with json files for all images  in the SONIC study named with the ID of the respective images. You can use those filenames to create the labels.

**Comment by geoffreyangus** [comment]
understood, thank you so much!
