### ISSUE TITLE
ISIC images

### ISSUE THREAD

**Issue by dkaizhang** [laura-rieger/deep-explanation-penalization#13]
Since the ISIC archive has changed, it's not clear anymore which images you used to train the models for the ISIC experiments. Specifically, it's unclear which images without patches were used. Would you be able to provide a table with the names of the included ISIC images? 

Thanks!

**Comment by laura-rieger** [comment]
Hi Kai, 
unfortunately I don't have the names or images anymore. I have since changed affiliation and don't have access to my old data anymore.
Best, Laura

**Comment by j-bl** [comment]
Hi Laura,

Similarly to Kai, I would also be interested in which ISIC data was used and would be happy to contact your former organization. However, from the affiliations listed in the paper, it is not clear to me whether you refer to the data being at the Technical University Denmark or at UC Berkeley. Could you help me by clarifying which group you are referring to?

Best,
Jan
