### ISSUE TITLE
Downloading data for the ISIC experiments

### ISSUE THREAD

**Issue by expectopatronum** [laura-rieger/deep-explanation-penalization#3]
Hi! 
I am trying to download the data for the reported ISIC experiments using the scripts you provided. I encountered the following issues:
* `00_download_metadata.py` prints `Fetching metadata for 23906 images`. The paper states `The ISIC dataset consists of 21,654 images (19,372 benign)`. How can I figure out which images you used?
* `01_download_imgs.py` only downloads 50 images although in the config the value is set to 25000. Am I expected to change `start_offset = 0` or the limit parameter in the URL somehow? 

Thanks a lot for the great work!
Best regards
Verena

**Comment by laura-rieger** [comment]
Hi Verena,

glad that you liked the work!
We excluded images with an indeterminate or unknown  diagnosis so only images that were diagnosed as either 'benign' or 'malignant' were included (see 02_sort_imgs.py l.38-44). We'll make this more clear in the final paper, thanks for pointing it out.

The start_offset is counted up in l.31 in script 01_download_imgs.py, so it should work as it is.  Did the script finish after 50 images or was it hanging? I'll look into it in any case.

Best, Laura

**Comment by laura-rieger** [comment]
It should be fixed now, there was a weird typo in l. 18 (used modulo instead of division).

**Comment by expectopatronum** [comment]
Thanks! It works! I am not sure if I should/can close it since you reopened it :)

**Comment by laura-rieger** [comment]
Super!

**Comment by Juna2** [comment]
Hi, again.
I'm trying to download the ISIC dataset with 01_download_imgs.py file but
it takes too much time to download it.(more than 9 hours sometimes 11 hours)
Is there something that I missed?
And at the ISIC site, they have more than 25000 images. so I don't know which images to download.
Any advice?

**Comment by laura-rieger** [comment]
Hi again, I'm fairly sure the downloading speed is an issue on their side and I don't know of a way to resolve it. I followed their recommendations for the API, so they may have updated it in the meantime. 

If you go to the gallery you'll find that some images don't have a diagnosis or don't have a definite diagnosis. The script won't include those images in the dataset so you don't need to choose which images to download.

**Comment by Juna2** [comment]
I eventually managed to download them all haha
In order to make it quick, I terminated the downloading process and start again a few times.
And when I start again I skipped all previously downloaded files.
The process tends to slow down over time.
