### ISSUE TITLE
How do I get segmentation files of ISIC dataset?

### ISSUE THREAD

**Issue by Juna2** [laura-rieger/deep-explanation-penalization#5]
Hi, I appreciate your awesome code!!
Btw how do I get segmentation files of the ISIC dataset?
I can't find any code in 02_sort_imgs.py that save 
segmentation files in "segmentation_path = os.path.join(data_path, "segmentation")"

I found in another issue that I can download SONIC study in ISIC website
but I still don't know if this data is already included in the dataset I can download with 
01_download_imgs.py file.

So which data of the study in the ISIC dataset did you exactly use for the ISIC result in your paper?
There were the following studies.

2018 JID Editorial Images (0 / 100)
Dermoscopedia (CC-BY) (0 / 5)
HAM10000 (0 / 10015)
MSK-1 (0 / 1100)
MSK-2 (0 / 1535)
MSK-3 (0 / 225)
MSK-4 (0 / 947)
MSK-5 (0 / 111)
SONIC (9251)
UDA-1 (0 / 557)
UDA-2 (0 / 60)

**Comment by laura-rieger** [comment]
Hi Jeon,
glad you like the work!
The segmentations need to be downloaded manually. I put them in a Google Drive [here](https://drive.google.com/drive/folders/1Er2PQMwmDSmg3BThyeu-JKX442OkQJit?usp=sharing)
I am not entirely sure I understand your second question. We used all images in the ISIC dataset (so including the SONIC dataset) barring images that did not have a conclusive diagnosis. Does this answer your question?
Best, Laura

**Comment by Juna2** [comment]
OMG sorry
I didn't know that the link was in readme.md!!!
Thank you so much for such a quick reply. I appreciate that.

**Comment by laura-rieger** [comment]
No worries, I just added the link after you pointed out that it's not currently there, so that was on me.
